### ISSUE TITLE
textDocument/references unexpected panic: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/go-langserver#146]
```
--> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///Users/nick/code/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go","languageId":"go","version":1,"text":"package app\n\nimport (\n\t\"net/http\"\n\n\t\"sourcegraph.com/sourcegraph/sourcegraph/app/internal\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/oauth2client\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/redirects\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/ui\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/app/router\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/pkg/auth\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/pkg/conf\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/pkg/eventsutil\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/pkg/httptrace\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/services/ext/github\"\n\thttpapiauth \"sourcegraph.com/sourcegraph/sourcegraph/services/httpapi/auth\"\n)\n\n// NewHandler returns a new app handler that uses the provided app\n// router (or creates a new one if nil).\nfunc NewHandler(r *router.Router) http.Handler {\n\tif r == nil {\n\t\tr = router.New(nil)\n\t}\n\n\tauth.InitSessionStore(conf.AppURL.Scheme == \"https\")\n\n\tm := http.NewServeMux()\n\n\tm.Handle(\"/\", r)\n\n\tr.Get(router.RobotsTxt).Handler(httptrace.TraceRoute(http.HandlerFunc(robotsTxt)))\n\tr.Get(router.Favicon).Handler(httptrace.TraceRoute(http.HandlerFunc(favicon)))\n\n\tr.Get(router.SitemapIndex).Handler(httptrace.TraceRoute(internal.Handler(serveSitemapIndex)))\n\tr.Get(router.RepoSitemap).Handler(httptrace.TraceRoute(internal.Handler(serveRepoSitemap)))\n\n\tr.Get(router.Logout).Handler(httptrace.TraceRoute(internal.Handler(serveLogout)))\n\n\t// Redirects\n\tr.Get(router.OldToolsRedirect).Handler(httptrace.TraceRoute(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n\t\thttp.Redirect(w, r, \"/beta\", 301)\n\t})))\n\n\tr.Get(router.UI).Handler(ui.Router())\n\n\tr.Get(router.GitHubOAuth2Initiate).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGitHubOAuth2Initiate)))\n\tr.Get(router.GitHubOAuth2Receive).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGitHubOAuth2Receive)))\n\tr.Get(router.GoogleOAuth2Initiate).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGoogleOAuth2Initiate)))\n\tr.Get(router.GoogleOAuth2Receive).Handler(httptrace.TraceRoute(internal.Handler(oauth2client.ServeGoogleOAuth2Receive)))\n\n\tr.Get(router.GDDORefs).Handler(httptrace.TraceRoute(internal.Handler(serveGDDORefs)))\n\n\tvar h http.Handler = m\n\th = redirects.RedirectsMiddleware(h)\n\th = eventsutil.AgentMiddleware(h)\n\th = githubAuthMiddleware(h)\n\th = auth.CookieMiddleware(h)\n\th = httpapiauth.AuthorizationMiddleware(h)\n\n\treturn h\n}\n\nfunc serveLogout(w http.ResponseWriter, r *http.Request) error {\n\tauth.DeleteSession(w, r)\n\thttp.Redirect(w, r, \"/\", http.StatusFound)\n\treturn nil\n}\n\nfunc githubAuthMiddleware(next http.Handler) http.Handler {\n\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n\t\tctx := github.NewContextWithAuthedClient(r.Context())\n\t\tnext.ServeHTTP(w, r.WithContext(ctx))\n\t})\n}\n"}}
--> request #1: textDocument/hover: {"textDocument":{"uri":"file:///Users/nick/code/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go"},"position":{"line":20,"character":10}}
--> notif: $/cancelRequest: {"id":1}
--> request #2: textDocument/references: {"textDocument":{"uri":"file:///Users/nick/code/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go"},"position":{"line":20,"character":10},"context":{"includeDeclaration":true}}
<-- result #1: textDocument/hover: {"contents":[{"language":"go","value":"func NewHandler(r *Router) Handler"},{"language":"markdown","value":"NewHandler returns a new app handler that uses the provided app router (or creates a new one if nil). \n\n"}],"range":{"start":{"line":20,"character":5},"end":{"line":20,"character":15}}}
--> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///Users/nick/code/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/init.go","languageId":"go","version":1,"text":"package app\n\nimport (\n\t// Load in toolchain formatters.\n\t_ \"sourcegraph.com/sourcegraph/sourcegraph/app/internal/srclibsupport\"\n\t\"sourcegraph.com/sourcegraph/sourcegraph/app/internal/tmpl\"\n)\n\nfunc Init() {\n\ttmpl.LoadOnce()\n}\n"}}
panic serving textDocument/references: sync: unlock of unlocked mutex
goroutine 1399 [running]:
github.com/sourcegraph/go-langserver/langserver.panicf(0x45a1c0, 0xc43516c560, 0x5008fd, 0x2, 0xc4334a7490, 0x1, 0x1, 0xc421ac0c00, 0x51280)
	/Users/nick/code/gopath/src/github.com/sourcegraph/go-langserver/langserver/util.go:47 +0x93
github.com/sourcegraph/go-langserver/langserver.(*LangHandler).Handle.func1(0xc42df16190, 0xc4334a7e20)
	/Users/nick/code/gopath/src/github.com/sourcegraph/go-langserver/langserver/handler.go:103 +0xd7
panic(0x45a1c0, 0xc43516c560)
	/usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:458 +0x243
sync.(*Mutex).Unlock(0xc42009a458)
	/usr/local/Cellar/go/1.7.4_2/libexec/src/sync/mutex.go:111 +0x104
sync.(*Once).Do(0xc42009a458, 0xc4334a7840)
	/usr/local/Cellar/go/1.7.4_2/libexec/src/sync/once.go:46 +0x94
github.com/sourcegraph/go-langserver/langserver.(*LangHandler).handleTextDocumentReferences(0xc42009a3f0, 0x709ee0, 0xc428739ce0, 0x7030a0, 0xc420075080, 0xc42df16190, 0xc428739c20, 0x55, 0x14, 0xa, ...)
	/Users/nick/code/gopath/src/github.com/sourcegraph/go-langserver/langserver/references.go:69 +0x261
github.com/sourcegraph/go-langserver/langserver.(*LangHandler).Handle(0xc42009a3f0, 0x709e60, 0xc42e322040, 0x7030a0, 0xc420075080, 0xc42df16190, 0x0, 0x0, 0x0, 0x0)
	/Users/nick/code/gopath/src/github.com/sourcegraph/go-langserver/langserver/handler.go:266 +0x2b13
github.com/sourcegraph/go-langserver/langserver.(*LangHandler).handle(0xc42009a3f0, 0x709ea0, 0xc420078178, 0xc420075080, 0xc42df16190, 0xc420176480, 0xc425de5b80, 0x4a, 0xc42464c6f8)
	/Users/nick/code/gopath/src/github.com/sourcegraph/go-langserver/langserver/handler.go:94 +0x66
github.com/sourcegraph/go-langserver/langserver.(*LangHandler).(github.com/sourcegraph/go-langserver/langserver.handle)-fm(0x709ea0, 0xc420078178, 0xc420075080, 0xc42df16190, 0xc42464c760, 0x1e6704, 0xc425de5b80, 0x4a)
	/Users/nick/code/gopath/src/github.com/sourcegraph/go-langserver/langserver/handler.go:27 +0x52
github.com/sourcegraph/jsonrpc2.HandlerWithError.Handle(0xc42011a7e0, 0x709ea0, 0xc420078178, 0xc420075080, 0xc42df16190)
	/Users/nick/code/gopath/src/github.com/sourcegraph/jsonrpc2/handler_with_error.go:14 +0x6f
created by github.com/sourcegraph/jsonrpc2.(*Conn).readMessages
	/Users/nick/code/gopath/src/github.com/sourcegraph/jsonrpc2/jsonrpc2.go:490 +0x82b
<-- error #2: textDocument/references: {"code":0,"message":"unexpected panic: sync: unlock of unlocked mutex","data":null}
[Error - 4:33:57 PM] Request textDocument/references failed.
  Message: unexpected panic: sync: unlock of unlocked mutex
  Code: 0 
```

**Comment by keegancsmith** [comment]
oops I missed this! I will fix straight away, may be indicative of a bad problem.

**Comment by keegancsmith** [comment]
@nicksnyder which commit are you running on? The line that is the source of the panic doesn't really make sense.

**Comment by keegancsmith** [comment]
Alright don't need to know the line. Given we only use sync.Once in one place, I believe I know the cause and have a fix.
